name: pv269-project
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hifiasm
  - minimap2
  - samtools
  - seqtk
  - seqkit
  - matplotlib
  - cairo
  - pip
  - pip:
    - moddotplot
    - nanoplot
    - quast
